#!/usr/bin/env python3
"""Generate BodyPaths.kt from the react-native-body-highlighter (MIT) SVG data.

Downloads the male front/back body-part path arrays and the two full-body
silhouette outlines, then emits Kotlin string constants the app renders with
Compose PathParser. Pinned to a specific commit so runs are deterministic.

Usage:  python3 vibe/generate_body_paths.py
"""

import os
import re
import sys
import urllib.request

REPO = "HichamELBSI/react-native-body-highlighter"
COMMIT = "15df9e2dbc621450001960bed5a30e6a75357faa"  # v3.2.0
RAW = f"https://raw.githubusercontent.com/{REPO}/{COMMIT}"

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "app/src/main/java/com/valerochka1337/valerochkagym/ui/analysis/body/BodyPaths.kt",
)


def fetch(path: str) -> str:
    with urllib.request.urlopen(f"{RAW}/{path}") as resp:
        return resp.read().decode("utf-8")


def match_braces(text: str, open_idx: int) -> int:
    """Return the index just past the '}' matching the '{' at open_idx."""
    depth = 0
    for i in range(open_idx, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i + 1
    raise ValueError("unbalanced braces")


def parse_body(text: str) -> "list[tuple[str, list[str]]]":
    """Parse a bodyFront/bodyBack.ts into [(slug, [path-d, ...]), ...] in file order."""
    result = []
    for m in re.finditer(r'slug:\s*"([^"]+)"', text):
        slug = m.group(1)
        path_kw = text.index("path:", m.end())
        brace = text.index("{", path_kw)
        end = match_braces(text, brace)
        block = text[brace:end]
        # SVG path data never contains a double quote, so every quoted string in
        # the path block (left/right/common arrays) is one path we want.
        paths = re.findall(r'"([^"]+)"', block)
        result.append((slug, paths))
    return result


def parse_silhouettes(text: str) -> "list[str]":
    """The two long border `d="..."` outlines from SvgMaleWrapper (front, then back)."""
    return re.findall(r'd="(M[^"]+)"', text)


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def kt_object(name: str, silhouette: str, muscles: "list[tuple[str, list[str]]]") -> str:
    lines = [
        f"object {name} {{",
        "    const val VIEWPORT_W: Float = 724f",
        "    const val VIEWPORT_H: Float = 1448f",
        "",
        f'    const val silhouette: String = "{esc(silhouette)}"',
        "",
        "    val muscles: Map<String, List<String>> = mapOf(",
    ]
    for slug, paths in muscles:
        lines.append(f'        "{slug}" to listOf(')
        for p in paths:
            lines.append(f'            "{esc(p)}",')
        lines.append("        ),")
    lines.append("    )")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    front = parse_body(fetch("assets/bodyFront.ts"))
    back = parse_body(fetch("assets/bodyBack.ts"))
    silhouettes = parse_silhouettes(fetch("components/SvgMaleWrapper.tsx"))
    if len(silhouettes) != 2:
        print(f"expected 2 silhouettes, got {len(silhouettes)}", file=sys.stderr)
        return 1
    front_outline, back_outline = silhouettes

    header = (
        "package com.valerochka1337.valerochkagym.ui.analysis.body\n"
        "\n"
        "// GENERATED by vibe/generate_body_paths.py — do not edit by hand.\n"
        "//\n"
        "// Body SVG path data from HichamELBSI/react-native-body-highlighter (MIT license),\n"
        f"// v3.2.0, commit {COMMIT[:7]}. Male model.\n"
        "// Front viewBox \"0 0 724 1448\"; back viewBox \"724 0 724 1448\" (x-offset +724,\n"
        "// normalized to 0..724 at parse time). Values are raw SVG `d` strings.\n"
    )
    body = "\n\n".join(
        [
            kt_object("BodyFrontPaths", front_outline, front),
            kt_object("BodyBackPaths", back_outline, back),
        ]
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header + "\n" + body + "\n")

    print(f"wrote {OUT}")
    print(f"  front: {len(front)} slugs, back: {len(back)} slugs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
